[manager]
54.92.238.58 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[workers]
54.172.83.0 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem
3.225.5.100 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[controller]
34.201.144.175 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3

